### ISSUE TITLE
Arc browser main pane not supported when sidebar is open

### ISSUE THREAD

**Issue by snam24** [godbout/Scrolla.docs#19]
Thanks so much for the awesome app. I enjoy the mouse-less life with Scrolla.

When the sidebar (of the [arc browser](https://arc.net/)) is open, the scrolla doesn't recognize the main pane of the browser. Please see the screenshots below.

*not working in the main pane*
<img width="2017" alt="ScreenShot_2023-05-29 at 09 20 55" src="https://github.com/godbout/Scrolla.docs/assets/83625480/de8d8394-258c-437f-b138-686ee3a68ce0">

*working fine with the sidebar closed*
<img width="2559" alt="ScreenShot_2023-05-29 at 09 21 26" src="https://github.com/godbout/Scrolla.docs/assets/83625480/f4cda86f-07e2-4d2e-a68a-f59da03c902a">

**Comment by godbout** [comment]
please check https://github.com/godbout/Scrolla.docs/issues/15
that should answer your questions and provide a solution.

please keep pinging if you have more thoughts.

**Comment by snam24** [comment]
Changing the Scrolla setting worked. Thanks!

**Comment by godbout** [comment]
yeah, web browsers (and Electron apps) are tricky because it's custom shits and a lots of Accessibility data is missing. but overall that option being ON should be useful coz it's gonna hide areas in native apps when you can't scroll anyways.

try it a few days and if all good then we can close this issue. thanks!
