### ISSUE TITLE
Allow passthrough

### ISSUE THREAD

**Issue by jannis-baum** [godbout/Scrolla.docs#7]
Like in kV, it would be great to allow modifiers like command to *passthrough*, i.e. deactivating Scrolla to send the keystrokes to the underlying app

**Comment by godbout** [comment]
yes, i've had this in mind. i'm still exploring. currently hotkeys passthrough (you can launch Alfred, iTerm, Spotlight, blah blah blah), and i override some stuff like `command w` that closes Scrolla rather than the underlying app. still need some research to figure out what's the best mix. will check deeper, thanks.

**Comment by godbout** [comment]
hmm. with kV i'm using an event tap callback. returning an event there will dispatch it back to macOS, which allows for the passthrough. in Scroll i use a local monitor for events, so that we can use it in SecureInput fields. but returning an event doesn't seem to dispatch it. so it seems that currently, or it's the passthrough, or it's the SecureInput fields... hopefully i'm just missing something. although i've already had my coffee. so, not a good start.

**Comment by godbout** [comment]
i'm trying to sending key events directly from within my events controller, but then the local monitor catches them, and then i get the loop of death 🤣️ constant beeping. like 1k events looping per sec. awesome stuff.

**Comment by godbout** [comment]
added in a4: https://github.com/godbout/Scrolla.docs/releases/tag/1.a4

see if it works well. if yes we can close!

**Comment by jannis-baum** [comment]
Looks great!
